# Generated by Django 4.1.3 on 2022-11-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(max_length=100)),
                ('format', models.CharField(choices=[('CSV', 'CSV'), ('XML', 'XML')], max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('schedule', models.CharField(choices=[('No Repeat', 'No Repeat'), ('Specific Date', 'Specific Date'), ('Daily', 'Daily'), ('Weekly', 'Weekly')], max_length=15)),
                ('time', models.TimeField(null=True)),
                ('date', models.DateField(null=True)),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=15, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
